name: Release Go
on:
  workflow_dispatch:
  release:
    types: [created,published]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Build server binary
        uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.36
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          project_path: "server.go"
          binary_name: "Server"
      - name: Build client binary
        uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.36
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod
          project_path: "client.go"
          binary_name: "Client"
