name: Go Build and Release
on:
  release:
    types: [created,published]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Build
        run: make all

      - name: Get Latest Release ID
        id: get_latest_release
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(response.data[0].id);

      - name: Upload Server Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: server
          asset_name: server
          asset_content_type: application/octet-stream

      - name: Upload Client Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: client
          asset_name: client
          asset_content_type: application/octet-stream
