name: Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go 1.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build server and client
        run: make

      - name: Zip server and client
        run: |
          zip server.zip server
          zip client.zip client

      - name: Upload server asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./server.zip
          asset_name: server.zip
          asset_content_type: application/zip

      - name: Upload client asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./client.zip
          asset_name: client.zip
          asset_content_type: application/zip
