name: Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go 1.2
        run: |
          chmod +x install_go.sh
          ./install_go.sh

      - name: Install dependencies
        run: apt-get update && apt-get install -y make

      - name: Build server and client
        run: make

      - name: Zip server and client
        run: |
          apt-get install -y zip
          zip server.zip server
          zip client.zip client

      - name: Upload server asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./server.zip
